---
### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "molecular blender - blender for quantum chemistry"
keywords:    "molecular blender, quantum chemistry"
description: "A plugin for importing molecules into blender and making publication quality images"
source_link: "https://github.com/smparker/molecular-blender"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

